name: flutter_basic_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  email_validator: ^3.0.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1 # Loading indicator
  google_fonts: ^6.2.1 # Beautiful fonts
  flutter_animate: ^4.5.0 # Animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
